services:
  - type: web
    name: flask-key-app
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
